name: Repthon-Baqir

# Controls when the workflow will run
on:
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: lint with isort and black
        run: | 
          echo هلو
      - uses: actions/checkout@v3
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'pylint: اشهدُ انَ علياً وليُ الله'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Repthon-Ar
          commit_user_email: 48654350+Repthon-Ar@users.noreply.github.com
          commit_author: Repthon-Ar <48654350+Repthon-Ar@users.noreply.github.com>
